# 04: Preparing the Training datasets

## 2D Scans

The first set of data that we will include in the training datasets were used for [the likelihood plots](https://github.com/Jorge-Alda/SMEFT19/blob/master/jupyter/PaperML/02_plotfits.ipynb)

In [1]:
import pandas as pd
import SMEFT19

/opt/conda/envs/smeft19/lib/python3.8/site-packages/xgboost/compat.py:93: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [2]:
dbf = SMEFT19.ellipse.load('../data/ellipses/rotBII.yaml')
bf = dbf['bf']

In [4]:
data_albl = pd.read_csv('../data/likelihood/likelihood_rotBII_l.dat', sep='\t')

In [5]:
data_albl.head()

,x,y,fast_likelihood_quarks.yaml,fast_likelihood_leptons.yaml,likelihood_ewpt.yaml,likelihood_eeww.yaml,likelihood_lept.yaml,likelihood_rd_rds.yaml,likelihood_lfu_fccc.yaml,likelihood_lfu_fcnc.yaml,likelihood_bcpv.yaml,likelihood_bqnunu.yaml,likelihood_lfv.yaml,likelihood_zlfv.yaml,likelihood_higgs.yaml,custom_beta,global
0,-0.156,-0.020800,5.918998,-0.851396,-0.090145,-0.000485,-0.000005,12.785751,-0.011174,-68.0,0.004540,0.43596,-121.704256,-0.000017,0.000566,-0.001531,-171.513194
1,-0.156,-0.019951,5.997012,-0.851443,-0.090180,-0.000479,-0.000005,12.785834,-0.011124,-68.0,0.004587,0.43596,-103.525727,-0.000017,0.000565,-0.001494,-153.256511
2,-0.156,-0.019102,6.071288,-0.851487,-0.090214,-0.000474,-0.000005,12.785913,-0.011077,-68.0,0.004632,0.43596,-87.522157,-0.000017,0.000564,-0.001459,-137.178532
3,-0.156,-0.018253,6.141888,-0.851530,-0.090246,-0.000468,-0.000005,12.785989,-0.011031,-68.0,0.004676,0.43596,-73.513089,-0.000017,0.000564,-0.001425,-123.098736
4,-0.156,-0.017404,6.208871,-0.851571,-0.090277,-0.000463,-0.000005,12.786061,-0.010988,-68.0,0.004717,0.43596,-61.325806,-0.000017,0.000563,-0.001393,-110.844348

In [6]:
dfsamplel = pd.DataFrame()

In [7]:
numpoints = len(data_albl)

In [10]:
dfsamplel['C'] = [bf[0]]*numpoints
dfsamplel['al'] = data_albl['x']
dfsamplel['bl'] = data_albl['y']
dfsamplel['aq'] = [bf[3]]*numpoints
dfsamplel['bq'] = [bf[4]]*numpoints
dfsamplel['likelihood'] = data_albl['global']

In [11]:
dfsamplel.head()

          C     al        bl        aq        bq  likelihood
0 -0.134958 -0.156 -0.020800 -0.051806  0.729542 -171.513194
1 -0.134958 -0.156 -0.019951 -0.051806  0.729542 -153.256511
2 -0.134958 -0.156 -0.019102 -0.051806  0.729542 -137.178532
3 -0.134958 -0.156 -0.018253 -0.051806  0.729542 -123.098736
4 -0.134958 -0.156 -0.017404 -0.051806  0.729542 -110.844348

In [13]:
dfsamplel.to_csv('../data/samples/samplealbl.dat', sep='\t', index=False)

In [14]:
data_aqbq = pd.read_csv('../data/likelihood/likelihood_rotBII_q.dat', sep='\t')
data_aqbq.head()

,x,y,fast_likelihood_quarks.yaml,fast_likelihood_leptons.yaml,likelihood_ewpt.yaml,likelihood_eeww.yaml,likelihood_lept.yaml,likelihood_rd_rds.yaml,likelihood_lfu_fccc.yaml,likelihood_lfu_fcnc.yaml,likelihood_bcpv.yaml,likelihood_bqnunu.yaml,likelihood_lfv.yaml,likelihood_zlfv.yaml,likelihood_higgs.yaml,custom_beta,global
0,-0.156,-0.560000,-184.042972,-1.474584,-0.179997,0.000009,-0.000001,-23.618556,0.041265,-16.459603,-0.004722,-0.412635,-0.044410,-0.000004,0.000200,0.000826,-226.196009
1,-0.156,-0.496327,-147.144271,-1.395568,-0.196670,0.000029,-0.000001,-21.194040,0.037345,-15.152440,-0.004775,-0.384979,-0.027611,-0.000004,0.000205,0.000815,-185.462779
2,-0.156,-0.432653,-110.755733,-1.314976,-0.212852,0.000048,-0.000002,-18.432544,0.032939,-13.523368,-0.004829,-0.351283,-0.017401,-0.000004,0.000209,0.000820,-144.579793
3,-0.156,-0.368980,-77.490612,-1.233929,-0.228057,0.000066,-0.000002,-15.375247,0.028047,-11.784730,-0.004878,-0.311083,-0.011184,-0.000004,0.000213,0.000842,-106.411399
4,-0.156,-0.305306,-49.622194,-1.153607,-0.241742,0.000082,-0.000002,-12.088953,0.022686,-9.811831,-0.004915,-0.264163,-0.007121,-0.000004,0.000217,0.000881,-73.171546

In [15]:
dfsampleq = pd.DataFrame()
numpoints = len(data_aqbq)
dfsampleq['C'] = [bf[0]]*numpoints
dfsampleq['al'] = [bf[1]]*numpoints
dfsampleq['bl'] = [bf[2]]*numpoints
dfsampleq['aq'] = data_aqbq['x']
dfsampleq['bq'] = data_aqbq['y']
dfsampleq['likelihood'] = data_aqbq['global']

In [16]:
dfsampleq.head()

          C        al            bl     aq        bq  likelihood
0 -0.134958  0.069719  1.155534e-08 -0.156 -0.560000 -226.196009
1 -0.134958  0.069719  1.155534e-08 -0.156 -0.496327 -185.462779
2 -0.134958  0.069719  1.155534e-08 -0.156 -0.432653 -144.579793
3 -0.134958  0.069719  1.155534e-08 -0.156 -0.368980 -106.411399
4 -0.134958  0.069719  1.155534e-08 -0.156 -0.305306  -73.171546

In [17]:
dfsampleq.to_csv('../data/samples/sampleaqbq.dat', sep='\t', index=False)

## Random points

In [3]:
from parscanning import RandomScan

In [4]:
RS = RandomScan(SMEFT19.likelihood_global, [-0.22, -0.15, -0.03, -0.12, 0],
                [-0.04, 0.15, 0.03, 0.075, 3.5], 10)

In [14]:
for i in range(11):
    RS.run_mp(4, SMEFT19.scenarios.rotBII)
    RS.write('../data/samples/randompoints.dat', 'at')
    RS.clear()

## Complete dataset

In [15]:
dataset = ['../data/likelihood/likelihood_rotBII_l.dat',
           '../data/likelihood/likelihood_rotBII_q.dat',
           '../data/samples/randompoints.dat']
dfs = [pd.read_csv(f, sep='\t', names=['C', 'al', 'bl', 'aq', 'bq', 'logL'],
                   header=0) for i, f in enumerate(dataset)]
df = pd.concat(dfs, ignore_index=True)

In [12]:
df.head()

          C          al        bl        aq        bq        logL
0  0.408385 -296.993324 -0.000014  0.000527 -0.000579 -345.946863
1  0.408385 -251.731517 -0.000014  0.000526 -0.000550 -300.614098
2  0.408385 -211.885360 -0.000014  0.000526 -0.000521 -260.700500
3  0.408385 -177.005505 -0.000014  0.000525 -0.000494 -225.756651
4  0.408385 -141.959130 -0.000014  0.000524 -0.000468 -190.613483

In [16]:
len(df)

9999

In [17]:
df.loc[df['logL'] > 10]

             C        al        bl        aq        bq       logL
314   0.410197 -4.067200 -0.000008  0.000316 -0.001075  10.973363
315   0.410197 -2.953133 -0.000008  0.000316 -0.001062  12.039980
316   0.410197 -2.140343 -0.000008  0.000316 -0.001051  12.805430
317   0.410197 -1.568895 -0.000008  0.000315 -0.001041  13.330591
318   0.410197 -1.185500 -0.000008  0.000315 -0.001032  13.669800
...        ...       ...       ...       ...       ...        ...
9986 -0.079966  0.134752 -0.002093 -0.025043  0.604992  18.728595
9987 -0.132337 -0.025493 -0.013187 -0.062529  0.788522  22.319630
9989 -0.078799 -0.063815  0.013170 -0.038361  0.886026  23.345626
9990 -0.048757  0.112502 -0.003944  0.017915  3.356377  12.972454
9998 -0.048338  0.116280  0.021421 -0.004961  3.247762  12.846077

[5998 rows x 6 columns]